"""change external_id

Revision ID: 46c152b14bff
Revises: 0001_create_vacancies
Create Date: 2026-02-18 13:22:19.476621
"""

from alembic import op
import sqlalchemy as sa


revision = '46c152b14bff'
down_revision = '0001_create_vacancies'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'external_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
